import type { TermsTemplate } from "@atlas/shared";

/**
 * Dois templates de termos globais (store_id = null). Os placeholders `{{...}}`
 * são resolvidos na geração do PDF. Espelhados em `supabase/seed.sql`.
 */
export const DEFAULT_TERMS_TEMPLATES: TermsTemplate[] = [
  {
    id: "10000000-0000-0000-0000-000000000001",
    storeId: null,
    name: "Padrão — Retirada em 90 dias",
    isDefault: true,
    body: [
      "TERMO DE ORDEM DE SERVIÇO",
      "",
      "Cliente: {{customerName}}",
      "Aparelho: {{deviceBrand}} {{deviceModel}} (IMEI: {{deviceImei}})",
      "",
      "Serviços e peças orçados totalizam R$ {{totalValue}}.",
      "Valor pago na entrada: R$ {{amountPaid}} ({{paymentMethod}}).",
      "Saldo restante: R$ {{balanceDue}}.",
      "Prazo estimado de conclusão: {{deadline}}.",
      "",
      "O cliente declara ciência de que, após a conclusão do reparo, deverá",
      "retirar o aparelho no prazo de até {{pickupDeadlineDays}} dias. Após esse",
      "período, poderão incidir taxas de armazenamento e o estabelecimento fica",
      "autorizado a dar destinação ao aparelho conforme a legislação vigente.",
      "",
      "Recebido por: {{receivedBy}}",
      "Emitido em: {{issuedAt}}",
      "",
      "Assinatura do cliente:",
    ].join("\n"),
  },
  {
    id: "10000000-0000-0000-0000-000000000002",
    storeId: null,
    name: "Detalhado — Com garantia do serviço",
    isDefault: false,
    body: [
      "TERMO DE ORDEM DE SERVIÇO E GARANTIA",
      "",
      "Cliente: {{customerName}}   Telefone: {{customerPhone}}",
      "Aparelho: {{deviceBrand}} {{deviceModel}}   Cor: {{deviceColor}}",
      "IMEI: {{deviceImei}}",
      "",
      "1. Valores",
      "   Total orçado: R$ {{totalValue}}",
      "   Pago na entrada: R$ {{amountPaid}} via {{paymentMethod}}",
      "   Saldo a pagar na retirada: R$ {{balanceDue}}",
      "",
      "2. Prazos",
      "   Conclusão estimada: {{deadline}}",
      "   Retirada: o cliente deve retirar o aparelho em até",
      "   {{pickupDeadlineDays}} dias após a conclusão. Decorrido o prazo,",
      "   aplicam-se taxas de guarda e as medidas previstas em lei.",
      "",
      "3. Garantia",
      "   O serviço executado possui garantia legal, limitada às peças e",
      "   serviços descritos nesta ordem, não cobrindo mau uso, quedas,",
      "   contato com líquidos ou violação por terceiros.",
      "",
      "Recebido por: {{receivedBy}}          Emitido em: {{issuedAt}}",
      "",
      "Declaro estar de acordo com os termos acima.",
      "Assinatura do cliente:",
    ].join("\n"),
  },
];
